# Generated by Django 2.2.12 on 2020-09-15 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_fitnessclass_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessclass',
            name='image',
        ),
    ]
